<<<

== Collection

=== Comparable vs Comparator

*Comparable* is used when we want to sort java object array or list, we need to implement java Comparable interface.
It's default/natural sorting.

*Comparator* interface provide different ways of sorting.
It's custom sorting.

* We should implement java Comparator interface to provide different ways of sorting.
* Comparable interface can be used to provide single way of sorting whereas, Comparator interface is used to provide different ways of sorting.
* For using Comparable, Class needs to implement it whereas for using Comparator we don’t need to make any change in the class.
* Comparable interface is in java.lang package whereas Comparator interface is present in java.util package.
* We don’t need to make any code changes at client side for using Comparable, Arrays.sort() or Collection.sort() methods automatically uses the compareTo() method of the class.
* For Comparator, client needs to provide the Comparator class to use in compare() method.

.Collection complexity table:
|===
.3+| Collection 8+| Time complexity | Space complexity |
4+|Average 4+|Worst| Worst | Remark
| Access | Search | Insertion | Deletion | Access | Search | Insertion | Deletion | All |

| Array | O(1) | O(n) | O(n) | O(n) | O(1) | O(n) | O(n) | O(n) | O(n) | -
| SingleLinkedList | O(n) | O(n) | O(1) | O(1) | O(n) | O(n) | O(1) | O(1) | O(n) |
| ArrayList | | | | | | | | | |
| LinkedList | | | | | | | | | |
| PriorityQueue | | | | | | | | | |
| HashSet | | | | | | | | | |
| LinkedHashSet | | | | | | | | | |
| TreeSet | | | | | | | | | |
| HashMap | | | | | | | | | |
| LinkedHashMap | | | | | | | | | |
| TreeMap | | | | | | | | | |
| Hashtable | | | | | | | | | |

|===

<<<