<<<

== Design patterns (Gang of Four (GoF))

=== Creational Design Patterns

Design patterns are a powerful tool for software developers.
However, they should not be seen as prescriptive specifications for software.
It is more important to understand the concepts that design patterns describe

==== Factory Method Pattern

A Factory Pattern or Factory Method Pattern says that just define an interface or abstract class for creating an object but let the subclasses decide which class to instantiate.
In other words, subclasses are responsible to create the instance of the class.

Advantage of Factory Design Pattern

* Factory Method Pattern allows the sub-classes to choose the type of objects to create.
* It promotes the loose-coupling by eliminating the need to bind application-specific classes into the code.
That means the code interacts solely with the resultant interface or abstract class, so that it will work with any classes that implement that interface or that extends that abstract class.

Example :
https://github.com/muku3011/LearnByExample/tree/master/DesignPattern/src/main/java/com/topics/creational/factory

==== Abstract Factory Pattern

Abstract Factory Pattern says that just define an interface or abstract class for creating families of related (or dependent) objects but without specifying their concrete sub-classes.That means Abstract Factory lets a class returns a factory of classes.
So, this is the reason that Abstract Factory Pattern is one level higher than the Factory Pattern.

Advantage of Abstract Factory Pattern

* Abstract Factory Pattern isolates the client code from concrete (implementation) classes.
* It eases the exchanging of object families.
* It promotes consistency among objects.

Example :
https://github.com/muku3011/LearnByExample/tree/master/DesignPattern/src/main/java/com/topics/creational/abstract_factory

==== Singleton Pattern

Singleton Pattern says that just"define a class that has only one instance and provides a global point of access to it".

There are two forms of singleton design pattern:

* Eager Instantiation: creation of instance at load time.
* Lazy Instantiation: creation of instance when required.

Advantage of Singleton design pattern

* Saves memory because object is not created at each request.
* Only single instance is reused again and again.

Usage of Singleton design pattern

* Singleton pattern is mostly used in multi-threaded and database applications.
* It is used in logging, caching, thread pools, configuration settings etc.

Example:
https://github.com/muku3011/LearnByExample/tree/master/DesignPattern/src/main/java/com/topics/creational/singleton

==== Prototype Pattern

Prototype Pattern says that cloning of an existing object instead of creating new one and can also be customized as per the requirement.
This pattern should be followed, if the cost of creating a new object is expensive and resource intensive.

Advantage of Prototype Pattern

* It hides complexities of creating objects.
* The clients can get new objects without knowing which type of object it will be.
* It lets you add or remove objects at runtime.

Usage of Prototype Pattern

* When the classes are instantiated at runtime.
* When the cost of creating an object is expensive or complicated.
* When you want to keep the number of classes in an application minimum.
* When the client application needs to be unaware of object creation and representation.

==== Builder Pattern

Builder pattern solves the issue with large number of optional parameters and inconsistent state by providing a way to build the object step-by-step and provide a method that will actually return the final Object.

Let’s see how we can implement builder design pattern in java.

* First of all you need to create a static nested class and then copy all the arguments from the outer class to the Builder class.
We should follow the naming convention and if the class name is Computer then builder class should be named as ComputerBuilder.
* Java Builder class should have a public constructor with all the required attributes as parameters.
* Java Builder class should have methods to set the optional parameters and it should return the same Builder object after setting the optional attribute.
* The final step is to provide a build() method in the builder class that will return the Object needed by client program.
For this we need to have a private constructor in the Class with Builder class as argument.

Here is the sample builder pattern example code where we have a Computer class and ComputerBuilder class to build it.

==== Object Pool Pattern ? (TODO)

=== Structural Design Patterns

Structural patterns provide different ways to create a class structure, for example using inheritance and composition to create a large object from small objects.

==== Adapter Design Pattern

Adapter design pattern is one of the structural design pattern and its used so that two unrelated interfaces can work together.
The object that joins these unrelated interface is called an Adapter.

One of the great real life example of Adapter design pattern is mobile charger.
Mobile battery needs 3 volts to charge but the normal socket produces either 120V (US) or 240V (India).
So the mobile charger works as an adapter between mobile charging socket and the wall socket.

We will try to implement multi-adapter using adapter design pattern in this tutorial.

So first of all we will have two classes – Volt (to measure volts) and Socket (producing constant volts of 120V).

Adapter Design Pattern Example in JDK Some of the adapter design pattern example I could easily find in JDK classes are;

* java.util.Arrays#asList()
* java.io.InputStreamReader(InputStream) (returns a Reader)
* java.io.OutputStreamWriter(OutputStream) (returns a Writer)

==== Composite Design Pattern

When we need to create a structure in a way that the objects in the structure has to be treated the same way, we can apply composite design pattern.

Lets understand it with a real life example – A diagram is a structure that consists of Objects such as Circle, Lines, Triangle etc.
When we fill the drawing with color (say Red), the same color also gets applied to the Objects in the drawing.
Here drawing is made up of different parts and they all have same operations.

Composite Pattern consists of following objects.

* Base Component – Base component is the interface for all objects in the composition, client program uses base component to work with the objects in the composition.
It can be an interface or an abstract class with some methods common to all the objects.
* Leaf – Defines the behaviour for the elements in the composition.
It is the building block for the composition and implements base component.
It doesnt’t have references to other Components.
* Composite – It consists of leaf elements and implements the operations in base component.

.Composite Pattern Base Component
Composite pattern base component defines the common methods for leaf and composites.
We can create a class Shape with a method draw(String fillColor) to draw the shape with given color.
Notice that composite also implements component and behaves similar to leaf except that it can contain group of leaf elements.

Composite Pattern Important Points:

* Composite pattern should be applied only when the group of objects should behave as the single object.
* Composite design pattern can be used to create a tree like structure.

java.awt.Container#add(Component) is a great example of Composite pattern in java and used a lot in Swing.

==== Proxy Design Pattern

Provide a surrogate or placeholder for another object to control access to it.

The definition itself is very clear and proxy design pattern is used when we want to provide controlled access of a functionality.

Let’s say we have a class that can run some command on the system.
Now if we are using it, its fine but if we want to give this program to a client application, it can have severe issues because client program can issue command to delete some system files or change some settings that you don’t want.

Here a proxy class can be created to provide controlled access of the program.

.Proxy Design Pattern – Main Class
Since we code Java in terms of interfaces, here is our interface and its implementation class.

==== Flyweight Design Pattern

Flyweight design pattern is used when we need to create a lot of Objects of a class.
Since every object consumes memory space that can be crucial for low memory devices, such as mobile devices or embedded systems, flyweight design pattern can be applied to reduce the load on memory by sharing objects.

==== Facade Design Pattern

Provide a unified interface to a set of interfaces in a subsystem.
Facade Pattern defines a higher-level interface that makes the subsystem easier to use.

Suppose we have an application with set of interfaces to use MySql/Oracle database and to generate different types of reports, such as HTML report, PDF report etc.

So we will have different set of interfaces to work with different types of database.
Now a client application can use these interfaces to get the required database connection and generate reports.

But when the complexity increases or the interface behavior names are confusing, client application will find it difficult to manage it.

So we can apply Facade design pattern here and provide a wrapper interface on top of the existing interface to help client application.

==== Bridge Design Pattern

Just like Adapter pattern, bridge design pattern is one of the Structural design pattern.
According to GoF bridge design pattern is "Decouple an abstraction from its implementation so that the two can vary independently"

The implementation of bridge design pattern follows the notion to prefer Composition over inheritance.

==== Decorator Design Pattern

Decorator design pattern is used to modify the functionality of an object at runtime.
At the same time other instances of the same class will not be affected by this, so individual object gets the modified behavior.

We use inheritance or composition to extend the behavior of an object but this is done at compile time and its applicable to all the instances of the class.
We can’t add any new functionality of remove any existing behavior at runtime – this is when Decorator pattern comes into picture.

Suppose we want to implement different kinds of cars – we can create interface Car to define the assemble method and then we can have a Basic car, further more we can extend it to Sports car and Luxury Car.

But if we want to get a car at runtime that has both the features of sports car and luxury car, then the implementation gets complex and if further more we want to specify which features should be added first, it gets even more complex.
Now imagine if we have ten different kind of cars, the implementation logic using inheritance and composition will be impossible to manage.
To solve this kind of programming situation, we apply decorator pattern in java.

=== Behavioral Design Patterns

Behavioral patterns provide solution for the better interaction between objects and how to provide lose coupling and flexibility to extend easily.

==== Template Method Pattern

Template Method is a behavioral design pattern and it’s used to create a method stub and deferring some of the steps of implementation to the subclasses.
Template method defines the steps to execute an algorithm and it can provide a default implementation that might be common for all or some of the subclasses.

Suppose we want to provide an algorithm to build a house.
The steps need to be performed to build a house are – building a foundation, building pillars, building walls, and windows.
The important point is that we can’t change the order of execution because we can’t build windows before building the foundation.
So, in this case, we can create a template method that will use different methods to build the house.
Check out Template Method Pattern post for implementation details with example program.

==== Mediator Pattern

The mediator design pattern is used to provide a centralized communication medium between different objects in a system.
The mediator design pattern is very helpful in an enterprise application where multiple objects are interacting with each other.
If the objects interact with each other directly, the system components are tightly coupled with each other that makes maintainability cost higher and not flexible to extend easily.
Mediator pattern focuses on to provide a mediator between objects for communication and help in implementing lose-coupling between objects.

Air traffic controller is a great example of a mediator pattern where the airport control room works as a mediator for communication between different flights.
The mediator works as a router between objects and it can have it’s own logic to provide a way of communication.
Check out Mediator Pattern post for implementation details with example program.

==== Chain of Responsibility Pattern

Chain of responsibility pattern is used to achieve loose coupling in software design where a request from the client is passed to a chain of objects to process them.
Then the object in the chain will decide themselves who will be processing the request and whether the request is required to be sent to the next object in the chain or not.

We know that we can have multiple catch blocks in a try-catch block code.
Here every catch block is kind of a processor to process that particular exception.
So when an exception occurs in the try block, it’s sent to the first catch block to process.
If the catch block is not able to process it, it forwards the request to next object in chain i.e next catch block.
If even the last catch block is not able to process it, the exception is thrown outside of the chain to the calling program.

ATM dispense machine logic can be implemented using Chain of Responsibility Pattern, check out the linked post.

==== Observer Pattern

Observer design pattern is useful when you are interested in the state of an object and want to get notified whenever there is any change.
In observer pattern, the object that watch on the state of another object are called Observer and the object that is being watched is called Subject.

Java provides an inbuilt platform for implementing Observer pattern through java.util.Observable class and java.util.Observer interface.
However, it’s not widely used because the implementation is really simple and most of the times we don’t want to end up extending a class just for implementing Observer pattern as java doesn’t provide multiple inheritances in classes.

Java Message Service (JMS) uses Observer pattern along with Mediator pattern to allow applications to subscribe and publish data to other applications.
Check out Observer Pattern post for implementation details and example program.

==== Strategy Pattern

Strategy pattern is used when we have multiple algorithm for a specific task and client decides the actual implementation to be used at runtime.

Strategy pattern is also known as Policy Pattern.
We define multiple algorithms and let client application pass the algorithm to be used as a parameter.
One of the best examples of this pattern is the Collections.sort() method that takes the Comparator parameter.
Based on the different implementations of Comparator interfaces, the Objects are getting sorted in different ways.

Check out Strategy Pattern post for implementation details and example program.

==== Command Pattern

Command Pattern is used to implement lose coupling in a request-response model.
In command pattern, the request is send to the invoker and invoker pass it to the encapsulated command object.
Command object passes the request to the appropriate method of Receiver to perform the specific action.

Let’s say we want to provide a File System utility with methods to open, write and close the file and it should support multiple operating systems such as Windows and Unix.

To implement our File System utility, first of all, we need to create the receiver classes that will actually do all the work.
Since we code in terms of Java interfaces, we can have FileSystemReceiver interface and it’s implementation classes for different operating system flavors such as Windows, Unix, Solaris etc.
Check out Command Pattern post for the implementation details with example program.

==== State Pattern

State design pattern is used when an Object change it’s behavior based on it’s internal state.

If we have to change the behavior of an object based on its state, we can have a state variable in the Object and use if-else condition block to perform different actions based on the state.
State pattern is used to provide a systematic and loosely coupled way to achieve this through Context and State implementations.

Check out State Pattern post for implementation details with example program.

==== Visitor Pattern

Visitor pattern is used when we have to perform an operation on a group of similar kind of Objects.
With the help of visitor pattern, we can move the operational logic from the objects to another class.

For example, think of a Shopping cart where we can add a different type of items (Elements), when we click on the checkout button, it calculates the total amount to be paid.
Now we can have the calculation logic in item classes or we can move out this logic to another class using visitor pattern.
Let’s implement this in our example of a visitor pattern.
Check out Visitor Pattern post for implementation details.

==== Interpreter Pattern

is used to defines a grammatical representation for a language and provides an interpreter to deal with this grammar.

The best example of this pattern is java compiler that interprets the java source code into byte code that is understandable by JVM. Google Translator is also an example of an interpreter pattern where the input can be in any language and we can get the output interpreted in another language.

Check out Interpreter Pattern post for example program.

==== Iterator Pattern

Iterator pattern in one of the behavioral pattern and it’s used to provide a standard way to traverse through a group of Objects.
Iterator pattern is widely used in Java Collection Framework where Iterator interface provides methods for traversing through a collection.

Iterator pattern is not only about traversing through a collection, but we can also provide different kind of iterators based on our requirements.
Iterator pattern hides the actual implementation of traversal through the collection and client programs just use iterator methods.
Check out Iterator Pattern post for example program and implementation details.

==== Memento Pattern

The memento design pattern is used when we want to save the state of an object so that we can restore later on.
Memento pattern is used to implement this in such a way that the saved state data of the object is not accessible outside of the object, this protects the integrity of saved state data.

Memento pattern is implemented with two objects – Originator and Caretaker.
The originator is the object whose state needs to be saved and restored and it uses an inner class to save the state of Object.
The inner class is called Memento and it’s private so that it can’t be accessed from other objects.

Check out Memento Pattern for sample program and implementation details.

<<<
