<<<

== Important topics

=== Assertion

Assertion is achieved using the assert statement in Java.
While executing assertion, it is believed to be true.
If it fails, JVM throws an error named AssertionError.
It is mainly used for testing purposes during development.

* Enable assertion: java -ea, java -enableassertions
* Disable assertion: java -da, java -disableassertions
* Don’t Use Assertions to Validate Arguments to a public Method.
* Do Use Assertions to Validate Arguments to a private Method.

==== Really simple

`assert (y > x);`

==== Simple

`assert (y > x) : "y is " + y + " x is " + x;`
Simple version adds a second expression separated from the first (boolean expression) by a colon—this expression's string value is added to the stack trace.
Both versions throw an immediate AssertionError.

=== Cloning

Object cloning refers to creation of exact copy of an object.
The java.lang.Cloneable interface must be implemented by the class whose object clone we want to create.
Implement Cloneable interface, and provide implementation for clone() CloneNotSupportedException.
It creates a new instance of the class of current object and initializes all its fields with exactly the contents of the corresponding fields of this object.

==== Shallow copy

Shallow copy is method of copying an object and is followed by default in cloning.
In this method the fields of an old object X are copied to the new object Y.
While copying the object type field the reference is copied to Y i.e object Y will point to same location as pointed out by X.
If the field value is a primitive type it copies the value of the primitive type.
Therefore, any changes made in referenced objects in object X or Y will be reflected in other object.

==== Deep copy

If we want to create a deep copy of object X and place it in a new object Y then new copy of any referenced objects fields are created and these references are placed in object Y.
This means any changes made in referenced object fields in object X or Y will be reflected only in that object and not in the other.
In below example, we create a deep copy of object.
A deep copy copies all fields, and makes copies of dynamically allocated memory pointed to by the fields.
A deep copy occurs when an object is copied along with the objects to which it refers.

==== Copy constructor

A way to copy an exixting object to a new object using class constructor by passing same class object to the constructor.
We can easily make it shallow or deep based on the requirement.

==== Copy factory

It's similar to copy constructor, only change is in place of constructor we create a static method to copy an object.

<<<